-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 15:57:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbgestionweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbgestionweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbgestionweb` DEFAULT CHARACTER SET utf8 ;
USE `dbgestionweb` ;

-- -----------------------------------------------------
-- Table `dbgestionweb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`categoria` (
  `idcategoria` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `dbgestionweb`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`subcategoria` (
  `idsubcategoria` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idsubcategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_categoria_subcategoria_idx` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_subcategoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbgestionweb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbgestionweb`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`permiso` (
  `idpermiso` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbgestionweb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`));


-- -----------------------------------------------------
-- Table `dbgestionweb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idciudad`));


-- -----------------------------------------------------
-- Table `dbgestionweb`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`comuna` (
  `idcomuna` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcomuna`));


-- -----------------------------------------------------
-- Table `dbgestionweb`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`direccion` (
  `iddireccion` INT NOT NULL AUTO_INCREMENT,
  `rut` INT NOT NULL,
  `dv` VARCHAR(1) NOT NULL,
  `correlativo` INT NOT NULL,
  `direccion1` VARCHAR(60) NOT NULL,
  `direccion2` VARCHAR(60) NULL,
  `idcomuna` INT NOT NULL,
  `idciudad` INT NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `celular` VARCHAR(20) NOT NULL,
  `email` VARCHAR(60) NULL,
  PRIMARY KEY (`iddireccion`, `rut`, `dv`, `correlativo`),
  INDEX `fk_idx` (`idciudad` ASC) VISIBLE,
  INDEX `fk_idx1` (`idcomuna` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad`
    FOREIGN KEY (`idciudad`)
    REFERENCES `dbgestionweb`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comuna`
    FOREIGN KEY (`idcomuna`)
    REFERENCES `dbgestionweb`.`comuna` (`idcomuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbgestionweb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `rut` INT NOT NULL DEFAULT 0,
  `dv` VARCHAR(1) NOT NULL DEFAULT 0,
  `razonsocial` VARCHAR(80) NOT NULL,
  `direccion` INT NOT NULL,
  PRIMARY KEY (`idempresa`, `rut`, `dv`),
  INDEX `fk_direccion_idx` (`direccion` ASC) VISIBLE,
  CONSTRAINT `fk_direccion`
    FOREIGN KEY (`direccion`)
    REFERENCES `dbgestionweb`.`direccion` (`iddireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbgestionweb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `idsubcategoria` INT NOT NULL,
  `idmarca` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(80) NOT NULL,
  `margenventa` INT NOT NULL,
  `precioventa` DOUBLE NOT NULL DEFAULT 0,
  `stock` DOUBLE NOT NULL,
  `preciolista` DOUBLE NOT NULL,
  `preciocompra` DOUBLE NOT NULL,
  `imagen` VARCHAR(100) NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `idempresa` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_produc_catego_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `fk_produc_subcateg_idx` (`idsubcategoria` ASC) VISIBLE,
  INDEX `fk_produc_marca_idx` (`idmarca` ASC) VISIBLE,
  INDEX `fk_produc_empresa_idx` (`idempresa` ASC) VISIBLE,
  CONSTRAINT `fk_produc_catego`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbgestionweb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produc_subcateg`
    FOREIGN KEY (`idsubcategoria`)
    REFERENCES `dbgestionweb`.`subcategoria` (`idsubcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produc_marca`
    FOREIGN KEY (`idmarca`)
    REFERENCES `dbgestionweb`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produc_empresa`
    FOREIGN KEY (`idempresa`)
    REFERENCES `dbgestionweb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbgestionweb`.`giro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`giro` (
  `idgiro` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idgiro`));


-- -----------------------------------------------------
-- Table `dbgestionweb`.`clientesproveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`clientesproveedor` (
  `rut` INT NOT NULL DEFAULT 0,
  `dv` VARCHAR(1) NOT NULL DEFAULT 0,
  `idgiro` INT NOT NULL DEFAULT 0,
  `direccion` INT NOT NULL DEFAULT 0,
  `credito` INT NOT NULL DEFAULT 0,
  `cancelado` INT NOT NULL DEFAULT 0,
  `saldo` INT NOT NULL DEFAULT 0,
  `contacto` VARCHAR(45) NULL,
  `tipo_persona` VARCHAR(1) NOT NULL DEFAULT 0,
  `activo` TINYINT(1) NOT NULL DEFAULT 0,
  `idempresa` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`rut`, `dv`),
  UNIQUE INDEX `Rut_UNIQUE` (`rut` ASC) VISIBLE,
  INDEX `fk_idx` (`idgiro` ASC) VISIBLE,
  INDEX `fkdireccion_idx` (`direccion` ASC) VISIBLE,
  INDEX `fk_cliente_empresa_idx` (`idempresa` ASC) VISIBLE,
  CONSTRAINT `fk_giro`
    FOREIGN KEY (`idgiro`)
    REFERENCES `dbgestionweb`.`giro` (`idgiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion`
    FOREIGN KEY (`direccion`)
    REFERENCES `dbgestionweb`.`direccion` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_empresa`
    FOREIGN KEY (`idempresa`)
    REFERENCES `dbgestionweb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbgestionweb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  `direccion` VARCHAR(80) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `cargo` VARCHAR(20) NULL DEFAULT NULL,
  `login` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(64) NOT NULL,
  `imagen` VARCHAR(50) NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idusuario`))
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbgestionweb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`));


-- -----------------------------------------------------
-- Table `dbgestionweb`.`encdctocompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`encdctocompra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `rut` INT NOT NULL,
  `dv` VARCHAR(1) NOT NULL,
  `tipodocumento` INT NOT NULL,
  `nrodcto` INT NOT NULL,
  `razonsocial` VARCHAR(80) NOT NULL,
  `neto` DECIMAL(11,2) NULL,
  `iva` DECIMAL(11,2) NULL,
  `total` DECIMAL(11,2) NULL,
  `fecha_dcto` DATETIME NULL,
  `fecha_proceso` DATETIME NULL,
  `estado` INT NULL,
  `idempresa` INT NULL,
  `idusuario` INT NULL,
  PRIMARY KEY (`idcompra`, `rut`, `dv`),
  INDEX `fk_empresa_idx` (`idempresa` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_empresa`
    FOREIGN KEY (`idempresa`)
    REFERENCES `dbgestionweb`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbgestionweb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado`
    FOREIGN KEY ()
    REFERENCES `dbgestionweb`.`estado` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbgestionweb`.`detdctocompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`detdctocompra` (
  `iddetcompra` INT NULL AUTO_INCREMENT,
  `idcompra` INT NOT NULL,
  `idproducto` INT NOT NULL DEFAULT 0,
  `correlativo` INT NOT NULL DEFAULT 1,
  `cantidad` DECIMAL(11,2) NOT NULL DEFAULT 1,
  `descripcion` VARCHAR(60) NOT NULL DEFAULT 'sin descripcion',
  `preciounitario` DECIMAL(11,2) NOT NULL DEFAULT 0,
  `descuento` DECIMAL(2,2) NOT NULL DEFAULT 0,
  `neto` DECIMAL(11,2) NOT NULL DEFAULT 0,
  `iva` DECIMAL(11,2) NOT NULL DEFAULT 0,
  `total` DECIMAL(11,2) NOT NULL DEFAULT 0,
  `idempresa` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`iddetcompra`),
  INDEX `fk_compra_idx` (`idcompra` ASC) VISIBLE,
  INDEX `fk_producto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_compra`
    FOREIGN KEY (`idcompra`)
    REFERENCES `dbgestionweb`.`encdctocompra` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `dbgestionweb`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dbgestionweb`.`usuario_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbgestionweb`.`usuario_permiso` (
  `idusuario_permiso` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  `idpermiso` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario_permiso`))
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
